/*
 * NewJPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-09-27 18:46:48
 */

/**
 *
 * @author pengruirui
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        newJPanel11 = new NewJPanel1();
        newJPanel21 = new NewJPanel2();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(-1);
        jSplitPane1.setResizeWeight(0.2);
        jSplitPane1.setLeftComponent(newJPanel11);
        jSplitPane1.setRightComponent(newJPanel21);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSplitPane jSplitPane1;
    private NewJPanel1 newJPanel11;
    private NewJPanel2 newJPanel21;
    // End of variables declaration//GEN-END:variables
}
