/*
 * Copyright(c) 2007-2011 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2011-06-17 17:24:41
 */
package com.nazca.inside.guide.client;

import com.nazca.ui.NInternalDiag;
import com.nazca.ui.NInternalDiagListener;
import com.nazca.ui.NLabelMessageTool;
import com.nazca.util.TimeFairy;
import com.nazca.inside.guide.client.ui.common.OKCancelPanelListener;
import com.nazca.inside.guide.client.util.UserUtil;
import com.nazca.inside.guide.client.util.InsideGuideResourceUtil;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author fred
 */
public class PasswordCheckPanel extends javax.swing.JPanel implements OKCancelPanelListener {

    /** Creates new form PasswordCheckPanel */
    public PasswordCheckPanel() {
        initComponents();
        okCancelPane.addOKCancelListener(this);
        okCancelPane.gotoNormalMode();
        userLb.setText(UserUtil.getName(ClientContext.getUser()));
        jLabel1.setIcon(NLabelMessageTool.getWarningIcon());
    }

    public boolean showMeForAuth(JComponent parent){
        jLabel1.setText("本操作在系统中是关键操作，请输入您的密码进行确认！");
        NInternalDiag<Boolean, JComponent> diag = new NInternalDiag<Boolean, JComponent>("密码认证", InsideGuideResourceUtil.readIcon("password-auth-32.png"), this);
        diag.addNInternalDiagListener(new NInternalDiagListener() {

            public void onClosing(NInternalDiag diag) {
            }

            public void onClosed(NInternalDiag diag) {
            }

            public void onShowingDone(NInternalDiag arg0) {
                okCancelPane.setDefaultOK();
            }
        });
        return diag.showInternalDiag(parent);
    }
    
    public boolean showMeForLock(JComponent parent){
        jLabel1.setText("客户端已经被锁定，请输入您的密码进行解锁！");
        NInternalDiag<Boolean, JComponent> diag = new NInternalDiag<Boolean, JComponent>("密码认证", InsideGuideResourceUtil.readIcon("password-auth-32.png"), this);
        diag.addNInternalDiagListener(new NInternalDiagListener() {

            public void onClosing(NInternalDiag diag) {
            }

            public void onClosed(NInternalDiag diag) {
            }

            public void onShowingDone(NInternalDiag arg0) {
                okCancelPane.setDefaultOK();
            }
        });
        okCancelPane.getCancelButton().setVisible(false);
        return diag.showInternalDiag(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userLb = new javax.swing.JLabel();
        pwdTxFd = new javax.swing.JPasswordField();
        okCancelPane = new com.nazca.inside.guide.client.ui.common.OKCancelPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("本操作在系统中是关键操作，请输入您的密码进行确认！");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("当前用户：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("输入密码：");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        userLb.setText("张三");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(userLb, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pwdTxFd, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(okCancelPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.nazca.inside.guide.client.ui.common.OKCancelPanel okCancelPane;
    private javax.swing.JPasswordField pwdTxFd;
    private javax.swing.JLabel userLb;
    // End of variables declaration//GEN-END:variables

    public void onOKClicked() {
        okCancelPane.gotoWaitMode("正在验证");
        pwdTxFd.setEnabled(false);
        new Thread() {
            public void run() {
                new TimeFairy().sleepIfNecessary();
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        if (ClientContext.isPasswordCorrect(new String(pwdTxFd.getPassword()))) {
                            NInternalDiag.findNInternalDiag(PasswordCheckPanel.this).hideDiag(true);
                        } else {
                            okCancelPane.gotoErrorMode("密码输入错误，请重新输入");
                            pwdTxFd.setEnabled(true);
                        }
                    }
                });
            }
        }.start();
    }

    public void onCancelClicked() {
        NInternalDiag.findNInternalDiag(PasswordCheckPanel.this).hideDiag(false);
    }
}
