/*
 * SystemMgmtPanel.java
 * 
 * Copyright(c) 2007-2013 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2013-08-20 17:02:54
 */
package com.nazca.inside.guide.client.ui.sysmodel;

import com.nazca.niis.client.ui.tabs.AbstractAppTabPanel;
import com.nazca.usm.client.UsmsMainPanel;
import com.nazca.inside.guide.client.ui.Destructable;
import com.nazca.inside.guide.client.util.InsideGuideResourceUtil;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.JPanel;

/**
 *
 * @author Zhang Chun Nan
 */
public class SystemMgmtPanel extends AbstractAppTabPanel implements Destructable {
    private Image activeIcon = InsideGuideResourceUtil.readImage("system-tab-active.png");
    private Image inactiveIcon = InsideGuideResourceUtil.readImage("system-tab-inactive.png");
    private JPanel userPane = null;

    /**
     * Creates new form SystemMgmtPanel
     */
    public SystemMgmtPanel() {
        initComponents();
        setTabText("系统管理");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPane = new javax.swing.JPanel();
        nNavToolBar1 = new com.nazca.ui.NNavToolBar();
        userBtn = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        centerPane.setLayout(new java.awt.BorderLayout());
        add(centerPane, java.awt.BorderLayout.CENTER);

        nNavToolBar1.setRollover(true);

        userBtn.setText("用户和权限管理");
        userBtn.setFocusable(false);
        userBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(userBtn);

        add(nNavToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        centerPane.removeAll();
        centerPane.add(userPane, BorderLayout.CENTER);
        centerPane.validate();
        centerPane.repaint();
    }//GEN-LAST:event_userBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPane;
    private com.nazca.ui.NNavToolBar nNavToolBar1;
    private javax.swing.JToggleButton userBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onInit() {
        setTabIcon(inactiveIcon);
        userPane = new JPanel();
        UsmsMainPanel usmsMainPane = new UsmsMainPanel();
        usmsMainPane.initAll();
        userPane = usmsMainPane;
        userBtn.doClick();
    }

    @Override
    public String getComponentUUID() {
        return SystemMgmtPanel.class.getName();
    }

    @Override
    public void onDestroy() {
    }

    @Override
    public void onShow() {
        setTabIcon(activeIcon);
    }

    @Override
    public void onHide() {
        setTabIcon(inactiveIcon);
    }
}
