/*
 * AboutIndideGuide.java
 * 
 * Copyright(c) 2007-2013 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2013-08-21 17:00:21
 */
package com.nazca.inside.guide.client.ui;

import com.nazca.ui.InternalDiagTool;
import com.nazca.ui.NDebugConsolePanel;
import com.nazca.ui.UIUtilities;
import com.nazca.util.OpenBrowser;
import com.nazca.inside.guide.client.ClientConfig;
import com.nazca.inside.guide.common.util.VersionHelper;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author blader
 */
public class AboutIndideGuide extends javax.swing.JPanel {
    /** Creates new form AboutIndideGuide */
    public AboutIndideGuide() {
        initComponents();
        versionLb.setText("版本：" + VersionHelper.getTotalVersion());
        this.jLinkLabel2.setForeground(Color.GRAY);
        this.jLinkLabel2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    OpenBrowser.openBrowser(ClientConfig.HELP_URL);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    public void showMe(Component parent){
        InternalDiagTool.showInternalDiag(parent, this, "关于", null, 680, 240);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyrightLb = new javax.swing.JLabel();
        logoLb = new javax.swing.JLabel();
        versionLb = new javax.swing.JLabel();
        jLinkLabel1 = new com.nazca.ui.JLinkLabel();
        jLinkLabel2 = new com.nazca.ui.JLinkLabel();
        copyrightLb1 = new javax.swing.JLabel();

        setOpaque(false);

        copyrightLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyrightLb.setText("溜溜球 版权所有");
        copyrightLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nazca/inside/guide/client/ui/res/logo-big.png"))); // NOI18N
        logoLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLbMouseClicked(evt);
            }
        });

        versionLb.setForeground(new java.awt.Color(102, 102, 102));
        versionLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLb.setText("版本：1.1.2.529");

        jLinkLabel1.setText("关闭“关于”");
        jLinkLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLinkLabel1MousePressed(evt);
            }
        });

        jLinkLabel2.setText("查看更新日志");

        copyrightLb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyrightLb1.setText("技术支持：北京英智兴达信息技术有限公司");
        copyrightLb1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(copyrightLb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(copyrightLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLinkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(versionLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLinkLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLb)
                    .addComponent(jLinkLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLinkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLinkLabel1MousePressed
        InternalDiagTool.hideInternalDiag(this);
    }//GEN-LAST:event_jLinkLabel1MousePressed

    private void logoLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLbMouseClicked
        if (UIUtilities.isLeftDoubleClick(evt)) {
            NDebugConsolePanel.showConsoleWindow();
        }
    }//GEN-LAST:event_logoLbMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLb;
    private javax.swing.JLabel copyrightLb1;
    private com.nazca.ui.JLinkLabel jLinkLabel1;
    private com.nazca.ui.JLinkLabel jLinkLabel2;
    private javax.swing.JLabel logoLb;
    private javax.swing.JLabel versionLb;
    // End of variables declaration//GEN-END:variables
}
