/*
 * InitPanel.java
 * 
 * Copyright(c) 2007-2013 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2013-08-28 17:29:50
 */
package com.nazca.inside.guide.client.ui;

import com.nazca.ui.laf.RoundSidePanelUI;
import com.nazca.ui.util.CardLayoutWrapper;
import com.nazca.inside.guide.client.db.BasicCodesSyncer;
import com.nazca.inside.guide.client.db.DBServiceControler;
import com.nazca.inside.guide.client.listener.SyncServerListener;

/**
 *
 * @author Zhang Chun Nan
 */
public class InitPanel extends javax.swing.JPanel implements Destructable, SyncServerListener {
    private CardLayoutWrapper card4init = null;
    /**
     * Creates new form InitPanel
     */
    public InitPanel() {
        initComponents();
        this.jPanel1.setUI(new RoundSidePanelUI());
        card4init = new CardLayoutWrapper(jPanel1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        failLb = new com.nazca.ui.AntialiasedLabel();
        waitingPanel1 = new com.nazca.ui.WaitingPanel();

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton3.setText("重新进行初始化");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jButton3, gridBagConstraints);

        failLb.setText("初始化失败，请点击下方按钮重试");
        failLb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(failLb, gridBagConstraints);

        jPanel1.add(jPanel3, "FAIL");

        waitingPanel1.setPrompt("正在初始化缓存，此过程可能持续1-2分钟，请耐心等待");
        jPanel1.add(waitingPanel1, "WAIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.showWaitingPane();
        new Thread() {
            public void run() {
                DBServiceControler.stopDBServer();
                DBServiceControler.startDBServer();
                BasicCodesSyncer.getInstance().syncNow();
            }
        }.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nazca.ui.AntialiasedLabel failLb;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private com.nazca.ui.WaitingPanel waitingPanel1;
    // End of variables declaration//GEN-END:variables

    private void showWaitingPane() {
        card4init.show(CardLayoutWrapper.WAIT);
    }

    @Override
    public void onInit() {
        showWaitingPane();
        new Thread(){
            public void run(){
                DBServiceControler.startDBServer();
                BasicCodesSyncer.getInstance().addListener(InitPanel.this);
                BasicCodesSyncer.getInstance().start();
            }
        }.start();
    }

    @Override
    public void onDestroy() {
        BasicCodesSyncer.getInstance().removeAllListeners();
    }

    @Override
    public void onSyncStart() {
    }

    @Override
    public void onSyncDone(boolean isReallySynced) {
        ClientFrame.getInstance().gotoWorkPlace();
    }

    @Override
    public void onSyncFailed(int errorCode, String msg) {
        card4init.show(CardLayoutWrapper.FAIL);
    }
}
