/*
 * NGroupListGroupPane.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-08-18 16:03:04
 */
package com.nazca.inside.guide.client.ui;

import java.awt.Color;
import com.nazca.ui.NSelectable;
import javax.swing.Icon;
import javax.swing.border.Border;

/**
 * NGroupList一级面板
 * @author Qiu Dongyue <qdy@yzhtech.com>
 */
public class NGroupListGroupPane extends javax.swing.JPanel implements NSelectable {
    private boolean selected;//是否是选中
    private boolean showLoading = false;

    /**
     * Creates new form ArticleListGroupItemPnl
     */
    public NGroupListGroupPane() {
        this("", "", false);
    }

    public NGroupListGroupPane(String leftT, String rightT, boolean isSelected) {
        initComponents();
        this.setLeftLabelText(leftT);
        this.setRightLabelText(rightT);
        leftLabel.setForeground(Color.decode("#3a648e"));
        leftLabel.setFont(leftLabel.getFont().deriveFont(leftLabel.getFont().getSize() + 2f));
        //baseLabel.setBorder(new EmptyBorder(10, 10, 10, 5));
        //baseLabel.setOpaque(false);
        this.selected = isSelected;
        setShowLoading(false);
    }

    @Override
    public void setSelected(boolean b) {
        this.selected = b;
        repaint();
    }

    public String getLeftLabelText() {
        return this.leftLabel.getText();
    }

    public String getRightLabelText() {
        return this.rightLabel.getText();
    }

    public void setLeftLabelText(String name) {
        leftLabel.setText(name);
    }

    public void setRightLabelText(String text) {
        this.rightLabel.setText(text);
    }
    
    public void setLeftLabelIcon(Icon icon){
        leftLabel.setIcon(icon);
    }

    /**
     * 设置宽高
     *
     * @param border
     */
    public void setLableBorder(Border border) {
        leftLabel.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();
        nLoading1 = new com.nazca.ui.NLoading();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 5));
        setOpaque(false);

        leftLabel.setText("sample");

        rightLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rightLabel.setText("sample");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nLoading1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(rightLabel)
                .addComponent(nLoading1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leftLabel))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel leftLabel;
    private com.nazca.ui.NLoading nLoading1;
    private javax.swing.JLabel rightLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the selected
     */
    public boolean isSelected() {

        return selected;
    }

    /**
     * @return the showLoading
     */
    public boolean isShowLoading() {
        return showLoading;
    }

    /**
     * @param showLoading the showLoading to set
     */
    public void setShowLoading(boolean showLoading) {
        this.showLoading = showLoading;
        if (showLoading) {
            nLoading1.setVisible(true);
            nLoading1.startAnim();
        } else {
            nLoading1.setVisible(false);
            nLoading1.stopAnim();
        }
    }

}
