/*
 * NGroupListNodePane.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-08-18 16:03:04
 */
package com.nazca.inside.guide.client.ui;

import com.nazca.ui.GraphicsTool;
import com.nazca.ui.UIUtilities;
import java.awt.Color;
import java.awt.Graphics;
import com.nazca.ui.NSelectable;
import java.awt.Graphics2D;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 * NGroupList二级面板
 * @author Qiu Dongyue <qdy@yzhtech.com>
 */
public class NGroupListNodePane extends javax.swing.JPanel implements NSelectable {
    private boolean selected;//是否是选中
    private boolean iconVisible;
    private static final Color c = Color.decode("#3e91d4");

    /**
     * Creates new form ArticleListGroupItemPnl
     */
    public NGroupListNodePane() {
        this("", false, false);
    }

    public NGroupListNodePane(String name, String rightText, boolean showLoading, boolean isSelected, boolean isIconVisible) {
        initComponents();
        this.setLeftLabelText(name);
        this.setRightLabelText(rightText);
        setLoadingShow(showLoading);
        this.selected = isSelected;
        this.setIconVisible(isIconVisible);
    }

    public NGroupListNodePane(String name, boolean isSelected, boolean isIconVisible) {
        this(name, "", false, isSelected, isIconVisible);
    }

    public NGroupListNodePane(String name, String rightText, boolean showLoading, boolean isSelected, boolean isIconVisible, Icon icon) {
        initComponents();
        if (icon != null) {
            leftLabel.setIcon(icon);
        }
        this.setLeftLabelText(name);
        this.setRightLabelText(rightText);
        setLoadingShow(showLoading);
        this.selected = isSelected;
        this.setIconVisible(isIconVisible);
    }

    public NGroupListNodePane(String name, String rightText, boolean isSelected) {
        this(name, rightText, false, isSelected, false);
    }

    public NGroupListNodePane(String name, String rightText, boolean isSelected, Icon icon) {
        this(name, rightText, false, isSelected, false, icon);
    }

    public NGroupListNodePane(String name, boolean isSelected, Icon icon) {
        this(name, "", false, isSelected, false, icon);
    }

    public void setLoadingShow(boolean show) {
        this.nLoading1.setVisible(show);
    }

    @Override
    public void setSelected(boolean b) {
        this.selected = b;
        repaint();
    }

    public String getLeftLabelText() {
        return this.leftLabel.getText();
    }

    public String getRightLabelText() {
        return this.rightLabel.getText();
    }

    public void setLeftLabelText(String name) {
        leftLabel.setText(name);
    }

    public void setRightLabelText(String text) {
        this.rightLabel.setText(text);
    }

    public void setLeftLabelIcon(Icon icon) {
        leftLabel.setIcon(icon);
    }

    /**
     * 设置宽高
     *
     * @param border
     */
    public void setLableBorder(Border border) {
        leftLabel.setBorder(border);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (selected) {
            g.setColor(c);
           // g.fillRect(0, 0, (int) (4 * UIUtilities.getScaleFact()), this.getHeight());
//            g.fillRect(0, 0, (int) (4 * UIUtilities.getScaleFactByFontScale()), this.getHeight());
        }
    }

    private Color rightBG = Color.decode("#3e91d4");

    private void paintRightLabel(Graphics g) {
        if (rightLabel.getText().isEmpty()) {
            return;
        }
        Graphics2D g2d = (Graphics2D) g.create();
        GraphicsTool.setQuanlifiedGraphics(g2d);
        g2d.setColor(rightBG);
        g2d.fillRoundRect(0, 0, rightLabel.getSize().width, rightLabel.getSize().height, 8, 8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftLabel = new javax.swing.JLabel();
        nLoading1 = new com.nazca.ui.NLoading();
        rightLabel = new JLabel(){
            public void paint(Graphics g){

                paintRightLabel(g);
                super.paint(g);
            }
        }
        ;

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 35, 8, 5));
        setOpaque(false);

        leftLabel.setText("left");

        rightLabel.setFont(rightLabel.getFont().deriveFont(rightLabel.getFont().getSize()-2f));
        rightLabel.setForeground(new java.awt.Color(255, 255, 255));
        rightLabel.setText("jLabel1");
        rightLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nLoading1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(leftLabel)
                .addComponent(nLoading1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rightLabel))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel leftLabel;
    private com.nazca.ui.NLoading nLoading1;
    private javax.swing.JLabel rightLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the iconVisible
     */
    public boolean isIconVisible() {
        return iconVisible;
    }

    /**
     * @param iconVisible the iconVisible to set
     */
    public void setIconVisible(boolean iconVisible) {
        this.iconVisible = iconVisible;
    }

    /**
     * @return the selected
     */
    public boolean isSelected() {

        return selected;
    }

}
